### ISSUE TITLE
McStasCalculator and Parameters

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/libpyvinyl#12]
Refactor the McStasCalculator and Parameters such that they derive from BaseCalculator and BaseParameters, respectively. Test these functionalities:

- [ ] Construct: `mcstascalculator = McStasCalculator(parameters=..., ...)`
- [ ] Copy construct  `mcstascalculator2 = mcstascalculator(parameters=new_parameters, ...)`
- [ ] `mcstascalculator.dump(fname="...")`
- [ ] Resurrect: `calculator = McStasCalculator(dumpfile=...)`
- [ ] perform a simulation:  `mcstascalculator = McStasCalculator(parameters=..., ...)`
- [ ] get handle on data `data = mcstascalculator.data`

**Comment by shervin86** [comment]
With McStasScript version > 0.0.42 McStasScript is using libpyvinyl version 1.1.0 and satisfy the requirements.
