### ISSUE TITLE
Legal and illegal values for Parameter class

### ISSUE THREAD

**Issue by shervin86** [PaNOSC-ViNYL/libpyvinyl#18]
I am trying to better define the use cases and make sure messy configurations to be avoided.
In the current implementation there are three quantities:
 - illegal intervals
 - legal intervals
 - options (or discrete values)

The user have hence the freedom to define any combination of them. I don't currently have in mind any use case where such a combination would be beneficial, and hence letting this opportunity to the user would just be more error prone.
It would be nice to hear from you such possible use cases and eventually add them in the commented part of the Parameter class to not forget about them.

Otherwise I would propose to simplify a bit the things as follows:
 - just one list of intervals
 - a bool defining if the list is of legal or illegal values
 - a method to add discrete values as intervals with the same min,max 
 - a method to set if intervals are to be considered as legal or not
 - a method to append intervals
```
    def add_option(self, option):
        """
        Sets allowed values for this parameter
        """
        self.intervals.append([option,option])
        self.intervals_are_legal = True

    def add_interval(self, min_value, max_value):
        """
        Sets an interval for this parameter, None for infinite
        """
        if min_value is None:
            min_value = -math.inf
        if max_value is None:
            max_value = math.inf

        self.intervals.append([min_value, max_value])

    def set_interval_as_legal(self, mybool):
         self.intervals_are_legal = mybool

```

What is your opinion about it?

**Comment by JunCEEE** [comment]
This looks simple and clear to me. In my daily usage, I would set either legal intervals or illegal intervals rather than set both at the same time. 
Maybe Mads has some special use cases for the initial version?

**Comment by mads-bertelsen** [comment]
I believe there are monochromator instruments where there are certain holes in the shielding that allows specific take off angles. There could then be single hole corresponding to one wavelength and a typical setting, and then a larger gap at another angle that allows for a continuum. In that situation I would add both an option and a legal interval. I agree using all three at once would be rare.

**Comment by JunCEEE** [comment]
I think @mads-bertelsen's example doesn't conflict with @shervin86's suggested code. Could we say that we've reached an agreement to adopt @shervin86's suggestions?

@shervin86 @mads-bertelsen

**Comment by shervin86** [comment]
If I understood correctly, that example is taken care by the proposed code. One can always do:
```
 par.add_option(single_legal_value)
 par.add_interval(min_continuum, max_continuum)
 par.set_interval_as_legal(True)
```

**Comment by JunCEEE** [comment]
@shervin86 Yes, it's exactly what I thought. Would you like to submit a pull request for that (then you will be shown as a contributor), or shall I do it?

**Comment by shervin86** [comment]
Please do it :-)

**Comment by JunCEEE** [comment]
@shervin86 When I was checking the ParametersTest I found a special case for `add_option`, where the value is not a number, but a bool or string. Regarding that, I would suggest having a separate `self.options` variable.

https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/5c9e0ab348a4c50aa914ac299027f290cf953f0c/tests/ParametersTest.py#L45-L55

**Comment by shervin86** [comment]
Well spotted. I forgot that the add_option designed by Mads was meant also to keep strings of allowed values and bools.
So I propose to let in unchanged by now.
