### ISSUE TITLE
Manuel comments about libpyvinyl implementaiton

### ISSUE THREAD

**Issue by shervin86** [PaNOSC-ViNYL/libpyvinyl#23]
I looked a bit more in libpyvinyl. I believe there are very good ideas but the structure must be simplified
and the implementation should be made at different levels of inheritance. 

I wanted to apply it to Shadow and my first trial was very complex.  The main reason is that I had to copy
all the calculator parameters in the new rigid structure. I forked the libpyvinyl repository and made some
test (limited only to shadow3 sources):
https://github.com/srio/libpyvinyl/blob/master/tests/Shadow3Calculator.py

Then, I made another experiment. I believe that we should incorporate the native parameters in our
parameters, in a very generic way, and avoid copying all the items. I propose to define only a very few
basic base/abstract classes with the list of the mandatory methods to be implemented, and then make
another top layer to implement the particular calculator.  My proposition to the generic classes is: 

https://github.com/srio/libpyvinyl/blob/master/libpyvinyl/VyBase.py

My implementation of the shadow3 binding to vinyl is:
https://github.com/srio/libpyvinyl/blob/master/libpyvinyl/VyShadow3.py

you see that the binding inheritates the 3 main classes and it interfaces them to the shadow3 methods and
objects, but does not create a duplicated list of parameters. The code is simple. Creating scripts with
Vinyl-shadow3 is as simple as in the native format (you can see it in the example included). The main work
is then concentrate in adequate the i/o (json, nexus, h5 etc) to be made at the level of the binding.
However, we can provide basic tools at the level of the abstract classes (e.g., dict to {json,h5} and
viceversa).

Let me know your feeling on that. 

I will be available for discussion in the December sprint to discuss these and other things.

**Comment by shervin86** [comment]
Dear @srio I see the annoying part in 
https://github.com/srio/libpyvinyl/blob/master/tests/Shadow3Calculator.py#L54
wouldn't be possible to have the oe0 parameters as a list?
```
oe0_dict = oe0.to_dictionary()
for param in self.parameters:
   v = getattr(oe0, param.name)
   v = param.value
```

**Comment by srio** [comment]
Thanks @shervin and @JunCEEE for your feedback. 

Thanks for your suggestion @shervin86. 

I managed to remove the list and pack all the variables automatically. See that in https://github.com/srio/libpyvinyl/blob/master/tests/Shadow3Calculator.py and https://github.com/srio/libpyvinyl/blob/master/notebooks/demo_pyvinyl_shadow3.py

I think this is satisfactory by now. But need more tests to be sure all the parameters are copied and retrieved correctly. 

I still think that it would be better to remove the copy of all the inputs. If not, it should be stated the kind of inputs allowed, for example a numpy array is not working (see  https://github.com/PaNOSC-ViNYL/libpyvinyl/issues/24). 

Rgds, Manuel-

**Comment by shervin86** [comment]
@srio I was looking at the demo notebook of your implementation.
Are all the parameters in the demo used? How many of them are supposed to be changed w.r.t. to the default values?
I think that in this notebooks, the possibility to print the list of parameters is really useful, for a non-expert user if the "unit" and "comment" fields are set in the initialization of the calculator. 
What do you think?

**Comment by srio** [comment]
Indeed, the list of shadow variables is very long and all of them must be defined. Depending on the system you want to simulate (mirror, crystal, etc) some of them are certainly not used. Listing all variables does not help much to the user, as they are quite cryptic.  Some variables are just flags that can have only a few values (e.g. -1, 0, 1, 2). Is it possible to check "limits" for that? 

Your idea is certainly valuable: I could include in the default the comment and also limits (or acceptable values) so the input is always checked. This is a good point. Right now, there is only txt help: 

https://github.com/oasys-kit/shadow3/blob/master/docs/source.nml
https://github.com/oasys-kit/shadow3/blob/master/docs/oe.nml

**Comment by shervin86** [comment]
Limits are certainly one of the main features we wanted to have. 
In #28 I'm changing a bit the interface to the limits, so I would wait till everyone is ok with the changes before implementing it.
Here's a snippet of how this might be:
```
my_parameter = Parameter("name", unit="MeV", comment="this is a mandatory variable")
my_parameter = 5 # this is a default value
my_paramter.add_interval(-1,2, True) # only values between -1 and 2 included are accepted
```
True means that this interval is a "legal" interval. Using False would imply that the interval is of forbidden values
We have not forced a check of the type... it might not be bad to have it, though.

**Comment by shervin86** [comment]
@srio can we follow up on the shadow3 implementation using the latest version of libpyvinyl?

**Comment by shervin86** [comment]
@srio  can we close this issue?
