### ISSUE TITLE
Data object

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/libpyvinyl#26]
Another suggestion by @srio ([meeting notes](https://github.com/PaNOSC-ViNYL/ViNYL-project/wiki/Sprint-2021#discussion-on-libpyvinyl) is to encapsulate simulation data in a Data class. Among others, this class would be responsible for IO (openpmd!). This would also open up a path towards in-memory passing of data between Calculators. 

@JunCEEE has a prototype in simex-lite, see  https://github.com/PaNOSC-ViNYL/ViNYL-project/issues/77

**Comment by JunCEEE** [comment]
There are already examples of data streaming reading and writing with openPMD-API.

https://openpmd-api.readthedocs.io/en/latest/usage/streaming.html#streaming

Considering the usage is based on a streaming file (e.g. "simData.sst"), I now feel that instead of fixing the data file format inside a calculator, it could be better to specify the data format as the calculator attribute.

Example:
```
interaction = InteractionCalculator()
interaction.input = "prop.h5"
interaction.input_format = "prop.h5"
interaction.output = "pmi.sst"
interaction.output_format = "openpmd"

diffraction = DiffractionCalculator()
diffraction.input = ''pmi.sst""
diffraction.input_format = "openpmd"
diffraction.output = "diffraction.nexus"
diffraction.output_fotmat = "nexus"
```
I'm also wondering if we really want to hold the "self.__data" in the calculator class because we will in the end analyze the data in the output file instead of doing so in the calculator class.

What if a calculator needs multiple input data? (e.g. InteractionCalculator needs sample data and wavefront data)

**Comment by JunCEEE** [comment]
A final usage example:

```
from SimExLite.Instrument import Instrument
from SimExLite.SourceCalculators import GenesisCalculator
from SimExLite.PropagationCalculators import WPGCalculator
from SimExLite.InteractionCalculators import XMDYNCalculator
from SimExLite.DiffractionCalculator import SKOPICalculator
from SimExLite.DetectorCalculator import DetectorCalculator


# Instantiate an instrument class.
spb = Instrument()

# Instantiate the calculators, the default parameters are initialized within the calculators.
source = GenesisCalculator()
propagation = WPGCalculator()
interaction = XMDYNCalculator()
diffraction = SKOPICalculator()
detector = DetectorCalculator()

# Add the different parts to the instrument class
spb.add(source)
spb.add(propagation)
spb.add(interaction)
spb.add(diffraction)
spb.add(detector)

# Run the simulation of a whole instrument.
spb.run()
```

**Comment by JunCEEE** [comment]
```
from SimExLite.SampleData import SampleData
from SimExLite.Instrument import Instrument
from SimExLite.SourceCalculators import GenesisCalculator
from SimExLite.PropagationCalculators import WPGCalculator
from SimExLite.InteractionCalculators import XMDYNCalculator
from SimExLite.DiffractionCalculator import SKOPICalculator
from SimExLite.DetectorCalculator import DetectorCalculator


spb = Instrument()
source = GenesisCalculator()
propagation = WPGCalculator()
interaction = XMDYNCalculator()
detector = DetectorCalculator()

# Tweak this diffraction calculator
diffraction = SKOPICalculator()
# Print out parameter information
diffraction.info()
# Connect data in the other format to the data input
# SampleData.convert will do the format convertion and return the converted data filename.
SampleData.convert(input='interaction/sample.xmdyn',input_format = 'xmdyn', output='interaction/sample.skopi',output_format='skopi')
diffraction.input = 'sample.skopi'
diffraction.output = 'diffr.h5'

spb.add(source)
spb.add(propagation)
spb.add(interaction)
spb.add(diffraction)
spb.add(detector)

spb.run()
```

**Comment by CFGrote** [comment]
Maybe a little historical remark might help: The `.__data` property was intended to hold the data returned from the backengine in cases where the backengine is a python object that would be constructed by the backengine() method of the calculator and returns the data it simulates. In SimEx there are examples for such calculators (maybe hidden away in some obscure never touched again branches). In the current state, we may not really need these type of calculator and hence, requiring that the simulation data (produced by whatever backengine code) becomes a property of the calculator can be relaxed. Writing this, I realize that it's not necessary. 

What we need is a machinery that produces valid openpmd (nexus) files from the "raw" simulation data produced by the backengine simulation code. This openpmd file should be enriched with metadata (physical parameters of instruments etc. and numerical parameters). See my earlier comment in libpyvinyl/DiffractionData/api_spec.py for a prototype exampe (I'll update it in a bit).

So in essence, having a Data class is still required but it should focus on handling the above functionality. Jun's example above (comment before this one) is a good starting point. I'd change strings for specifying input and output format by classes for reasons stated elsewhere. 

Ok, I'll try to pull another prototype example, maybe that will be more helpful than this lengthy detour.

**Comment by CFGrote** [comment]
I updated the api_spec.py prototype. 
Not happy yet as Parameters are missing and I'm not sure where to inject them into the IO machinery. Essentially, a OpenPMD / Data class should take care of formatting any format to openpmd.  Also have to reformat openpmd data into format expected by backengine code for input data. Is this done by the calculator? Probably not.

Guess this needs a couple more iterations.

**Comment by JunCEEE** [comment]
Thank you, Carsten. Inspired by you, I have a clearer idea now. I tried three options handling the data in the following pseudo-codes. It's clear to spot that option 1 to specify the data format in a calculator (if there is no native support) is not practical. Option 2 is suitable for a specific implementation but is not for a base class in libpyvinyl. Option 3 might be close to what we need: a requirement of a method to convert the native output to openPMD format. If the calculator backengine has native support of openPMD, then we can specify it as an input to construct the class. Since some metadata can only be taken in the calculator and probably will not be saved in its native format, that might have to be done by the calculator.

A data class is absolutely needed in an exact implementation(e.g. SimEx), but maybe not for libpyvinyl. 

Option 1: provide format interface in the calculator
```
diffraction = SKOPICalculator('DiffractionCalculator')
diffraction.info()
diffraction.input = ['photon.h5','sample.pdb']
diffraction.input_format = ['wpg','pdb']
# The data format needs to be provided.
# The supported data format should not be hard-coded here, instead, it is provided
# by the format class.
diffraction.output = 'diffration.h5'
diffraction.output = 'openPMD'
detector = GenericCalculator()
```
The calculator class in option 1:

```py
class SKOPICalculator(BaseCalculator):
    def __init__(self, name, input='interaction/pmi.h5', input_format='openpmd', output='diffraction/diffr.h5', output_format = 'nexus', parameters=None, dumpfile=None**kwargs):
        super().__init__(name, parameters, dumpfile, **kwargs)
        if not isinstance(self.parameters, CalculatorParameters):
            self.__initParameters()
    def backeingine():
        output_tmp = IOUtilities.getTmpFileName()
        if isinstance(input, string):
            convert(self.input, input_format, input_tmp)
            command_sequence = ['radiationDamageMPI',
                        '--inputDir',         str(),input_tmp
                        '--outputDir',        str(output_tmp),
                        '--geomFile',         str(self.parameters['beam_geometry_file']),
                        '--configFile',       str(self.parameters['config_file']),
                        '--uniformRotation',  str(self.parameters['uniform_rotation']),
                        '--calculateCompton', str(self.parameters['calculate_Compton']),
                        '--sliceInterval',    str(self.parameters['slice_interval']),
                        '--numSlices',        str(self.parameters['number_of_slices']),
                        '--pmiStartID',       str(self.parameters['pmi_start_ID']),
                        '--pmiEndID',         str(self.parameters['pmi_stop_ID']),
                        '--numDP',            str(self.parameters['number_of_diffraction_patterns']),
                        ]
            subprocess.run(command_sequence)
            convert(output_tmp, self.output_format, self.output_format)
        elif isinstance(input, list):
            command_sequence = ['DiffractionPDB',
             '--inputDir',         str(self.input[0]),
             '--beamFile',         str(self.input[1]),
             '--outputDir',        str(output_tmp)]

```

This is definitely not a good idea.


Option 2: provide format interface as not part of the calculator
```py
diffraction = SKOPICalculator()
diffraction.info()
diffraction.input = SampleData.convert(input='sample.xmdyn',input_fmt = 'xmdyn', output='sample.skopi',output_fmt='skopi')
diffraction.output = 'native.output'
DiffractionData.convert('native.ouput','native_format','openpmd.ouput','openpmd')
```
If the calculator has already an easy way to specify the data, we should be able to expose that in the interface.

Shadow example:
```py
shadow = ShadowCalculator(output=native_output)
shadow.backeingine()
ShadowData.convert('native.ouput','native_format','openpmd.ouput','openpmd')
```

Option 3: provide a data class to deal with the calculator
```py
shadow = ShadowCalculator(output='native_output_name', output_format='opmd')
shadow.backeingine()
```
```py
shadow = ShadowCalculator(output='native_output_name', output_format='native')
shadow.backeingine()
shadow.to_opmd()
```

**Comment by JunCEEE** [comment]
After the meeting with @mads-bertelsen and @shervin86, we got the following conclusions:
- A data class is needed to:
	- Support the calculators output in python object
	- Convert the native data into openPMD/nexus
	- Act as abstraction harmonizing the way to wrap multiple input and output files.
- The calculator should return a data class at the end
- The data class will not read the data files into memory by default but provide metadata and methods to read the data files into memory and convert the native output into openPMD/nexus
- libpyvinyl will only provide the base data class. The exact data class should be developed by the calculator developer.
- `calculator.input` could be a data class. I need more specific suggestions on `calculator.output` (can someone thinks about a use case of this attribute?)
- I will submit pseudo-codes based on our discussion and share the link. After the review/approval of the pseudo-codes, I will develop the BaseClass based on the pseudo-codes we agree with.

**Comment by JunCEEE** [comment]
Based on the discussion (https://github.com/PaNOSC-ViNYL/libpyvinyl/issues/26#issuecomment-987801571), I've updated the pseudo-codes in `api_spec_v2.py`. Please have a review on that first ([Link](https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/32/files#diff-86315c5523bf18b717f5bf8b09acbcea6e2a7344982e7ef2b9be554f0ec38764))

@shervin86 and @CFGrote, if you check the pseudo-codes carefully, you can see that I use `self.output` to hold the result of the calculator, and put it as the input of the next calculator. It's kind of intuitive. And watch out that the data class doesn't read the file into the memory automatically. It's an interface class, and it interacts with the memory only when `write` or `get` are called.

I know we have spent more time than expected on this topic, but I feel this is essential to the success of this project. I would like to invest more time discussing and don't mind spending time doing actual implementation during Xmas.

**Comment by mads-bertelsen** [comment]
I like the syntax!

I think I would make backengine() return a data collection object (object.output). The syntax in your file wouldn't change, you are just not capturing that output in a variable, but it would be there if needed and would be displayed if it was the late line in a jupyter notebook block.

I would like to see some example of how a DataCollection object is returned after the simulation, here we just see examples of how it is given as input.

**Comment by shervin86** [comment]
Thinking a bit more about it.
Your InteractionCalculator produces 10 output files in some native format and your DiffractionCalculator wants only 3 of them. How is this done?

One possible solution would be:
```
DataCollection outA = interaction.outputs(["out1","out2","out3"])
DataCollection outB = interaction.outputs(["other_outputs"])
...
diffraction.input = outA
```

**Comment by srio** [comment]
Just my opinion. I like the idea that calculator returns an object (data or data collection ) and 

```
shadow = ShadowCalculator()
data = shadow.backengine()
data.write(filename='native_output_name.dat', output_format='native')
```

the data object can be stored as an attribute in calculator, therefore the same effect is in 
```
shadow = ShadowCalculator(output='native_output_name.dat', output_format='native')
shadow.backengine()
shadow.write()
```

Here the calculator.write() will call internally data.write(), but the write method belongs to data. 

If you use calculators with several outputs, change data by dataCollection

**Comment by JunCEEE** [comment]
[libpyvinyl/DiffractionData/api_spec_v2.py](https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/32/files#diff-86315c5523bf18b717f5bf8b09acbcea6e2a7344982e7ef2b9be554f0ec38764): More realistic implementation pseudo-code.
[libpyvinyl/testBaseData.py](https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/32/files#diff-683f29a1c26c3c41124bf469c5f264dd3ce7a7b815300ba4bbc5eafd70904351): The exact implementation example of `BaseData`, `BaseFormat` and `DataCollection`.

I'm sorry that I'm late in finalizing the examples. Please focus on reviewing the above two files, many thanks.

**Comment by shervin86** [comment]
Everyhing done and integrated in version 1.1.1.
