### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/libpyvinyl#27]
Travis is broken, let's move to github actions: https://docs.github.com/en/actions/quickstart

**Comment by CFGrote** [comment]
The workflow should include
- [ ] Testing

**Comment by CFGrote** [comment]
Btw, the documentation is at https://readthedocs.org/projects/libpyvinyl/

**Comment by CFGrote** [comment]
Readthedocs builds documentation for branches master, develop, and tags latest, and stable. changes pushed to develop branch (251b001), will PR to master if doc builds ok.

**Comment by CFGrote** [comment]
CI on github actions is functional:
https://github.com/PaNOSC-ViNYL/libpyvinyl/actions/runs/1531239373

tests fail though ...

**Comment by CFGrote** [comment]
pushed to develop. please merge into your branches to get the CI setup (or cherry-pick f5cac3f).

**Comment by shervin86** [comment]
> Btw, the documentation is at https://readthedocs.org/projects/libpyvinyl/

Can you add the link in the description of the repository? This way the link is visible also from the main page on github.

**Comment by shervin86** [comment]
@CFGrote the develop branch is not up-to-date w.r.t. master.
Can you update it by a rebase w.r.t. master, please?

**Comment by shervin86** [comment]
> CI on github actions is functional: https://github.com/PaNOSC-ViNYL/libpyvinyl/actions/runs/1531239373
> 
> tests fail though ...

It seems that `3.10` is interpreted as a number and hence treated as 3.1 in the matrix list of python versions.
Should they be strings maybe?

**Comment by shervin86** [comment]
@CFGrote shall we close this issue?
