### ISSUE TITLE
libpyvinyl: Tag and release on github

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/libpyvinyl#59]
Releases of our software must not only be hosted on pypi or other package repositories but also directly on github. Follow the "Releases" section on the repository website.

**Comment by CFGrote** [comment]
Releases of our software must not only be hosted on pypi or other package repositories but also directly on github. Follow the "Releases" section on the repository website.

**Comment by CFGrote** [comment]
Do we have a tagged release yet?

**Comment by JunCEEE** [comment]
We have one here: https://github.com/PaNOSC-ViNYL/libpyvinyl/releases/tag/v1.1.0

**Comment by JunCEEE** [comment]
Done: https://github.com/PaNOSC-ViNYL/libpyvinyl/releases/tag/v1.1.0
