### ISSUE TITLE
questions concerning the use of libpyvinyl in shadow3-libpyvinyl

### ISSUE THREAD

**Issue by srio** [PaNOSC-ViNYL/libpyvinyl#77]
Hello, 
it looks like libpyvinyl is working good with shadow3. 

I upgraded the shadow3 interface project https://github.com/PaNOSC-ViNYL/shadow3-libpyvinyl
I incorporated the openPMD file format by @aljosahafner 

You find an example in https://github.com/PaNOSC-ViNYL/shadow3-libpyvinyl/blob/main/examples/demo_pyvinyl_shadow3.py

The use is basically: 
```
from shadow3libpyvinyl.Shadow3Calculator import Shadow3Calculator
from shadow3libpyvinyl.Shadow3Data import Shadow3OpenPMDFormat

from libpyvinyl.Parameters.Collections import CalculatorParameters
from libpyvinyl.Parameters.Parameter import Parameter


# prepare calculator parameters

parameters = CalculatorParameters()
p = Parameter("oe0.FDISTR"      , "" )  ; p.value   = 3                        ; parameters.add(p)
p = Parameter("oe0.F_COLOR"     , "" )  ; p.value   = 3                        ; parameters.add(p)
p = Parameter("oe0.F_PHOT"      , "" )  ; p.value   = 0                        ; parameters.add(p)
p = Parameter("oe0.HDIV1"       , "" )  ; p.value   = 0.0                      ; parameters.add(p)
p = Parameter("oe0.HDIV2"       , "" )  ; p.value   = 0.0                      ; parameters.add(p)
# etc etc to define everything shadow needs


# define calculator and run shadow3

calculator = Shadow3Calculator("test", None, parameters=parameters)
calculator.backengine()

# save files

calculator.parameters.to_json("my_parameters.json")
calculator.data.write("tmp11.h5", Shadow3OpenPMDFormat)  # openPMD data format
```

Just some questions to the libpyvinyl experts: 

1) Do you think the use of libpyvinyl is correct? Any suggestion to make it more clear or to better use the lib resources? 

2) I think the "adding parameter" could be improved. Now it needs three commands per parameter: 
```
p = Parameter("oe0.F_COLOR"     , "" )  ; p.value   = 3                        ; parameters.add(p)
```
It would be nicer to have a mechanism to assign the parameter value at the construction, something like: 

```
parameters.add(Parameter("oe0.F_COLOR"     , "", value=3 ) )
```
is there any reason why  Parameter() cannot take a value at the construction? Would you like to add it? 

3) @aljosahafner I copied the openPMD module into the shadow3-libpyvinyl module. It is then duplicated in the PaNOSC Oasys addon. As now PaNOSC add-on depends on shadow3-libpyvinyl , it would be nice to remove openPMD from PaNOSC addon and keep a single copy in shadow3-libpyvinyl . Do you agree? Shall I do it (or do it yourself)?

Thanks a lot!

**Comment by aljosahafner** [comment]
Hey, regarding 3. I think you can go ahead yourself. Of course I assume you will move it to this one?

**Comment by shervin86** [comment]
@srio there is a way to have an inline creation of the parameter:
```
 p = parameters.new_parameter("NAME", unit="UNIT", comment="COMMENT")
 p.value = 5
 p = parameters.new_parameter("NAME2", unit="UNIT2", comment="COMMENT2")
 p.value = 10
```
but there is currently no way to have an inline initialization of the parameter. The reason behind that is that when assigning the value there are also checks being performed on the allowed and forbidden values that can be set using the `.add_interval(...)` etc. methods. Having an inline initialization might be skip those checks. 
On the other hand one could use the `from_dict` class method, but I have never used that and personally I find it more cumberson that three commands. 

I don't have strong opinions, but I don't feel like you might gain much.
