### ISSUE TITLE
Add unit_tests of packages depending on libpyvinyl to github workflows

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/libpyvinyl#82]

**Comment by JunCEEE** [comment]
- [McStasScript](https://github.com/PaNOSC-ViNYL/McStasScript)
- SimEx-Lite
- [instrumentDataBaseAPI](https://github.com/PaNOSC-ViNYL/instrumentDataBaseAPI)

**Comment by JunCEEE** [comment]
Hi, @mads-bertelsen, I've done:
- removing `typing` dependency
- separating the tests;
- creating a preliminary procedure to test McStasScript in https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/removing_typying_dependency/.github/workflows/ci.yml

Please add the test procedures you would like to include for McStasScript here:
https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/7b596cf2d83ed8ce77b799ae8fc3d99249e47f68/.github/workflows/ci.yml#L25-L27

**Comment by CFGrote** [comment]
I don't understand this one, can you please add a more elaborate description @JunCEEE ?

**Comment by JunCEEE** [comment]
Hi, @CFGrote It's about adding McStasScript and SimEx-Lite unit tests to the CI. Now the task is finished. I think we can close it.
